"""Update election table to include election name

Revision ID: 1454d350ca40
Revises: f380fa2622c2
Create Date: 2024-09-14 20:41:37.552395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1454d350ca40'
down_revision = 'f380fa2622c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('election_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.drop_column('election_name')

    # ### end Alembic commands ###
